version: '3.8'

services:
  jupyter:
    image: jupyter-notebook-cust:${TAG:-v1.0.0}
    build: .
    ports:
      - "80:80"
    volumes:
      - ./notebooks:/workspace
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=80", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
